version: '2'
services:
  data:
    build:
  mysql:
    image: mysql
    environment:
    ports:
    volumes:
    volumes_from:
  react:
    image: nginx
    build:
    ports:
    volumes:
  api:
    build:
    ports:
    volumes:
